### ISSUE TITLE
Could not get unknown property 'mergeResourcesProvider' when running on Android

### ISSUE THREAD

**Issue by theodorusyoga** [react-native-elements/react-native-elements-storybook#15]
Steps to reproduce:
I got this error while running on Android: `yarn android` (`react-native run-android`). 

> Where:
Script '/Users/theoyoga/Documents/react-native-elements-storybook/node_modules/react-native/react.gradle' line: 95
What went wrong:
A problem occurred configuring project ':app'.
**> Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.**

Temporary solution: 
I found the issue and a quick workaround from this link: [facebook/react-native/24022#474717616](https://github.com/facebook/react-native/issues/24022#issuecomment-474717616). I solved it by upgrading gradle version and SDK versions, etc in `android/build.gradle`.

@haruelrovix  I also submitted a PR related to this error. Please take a look. 

Thanks.

**Comment by theodorusyoga** [comment]
@haruelrovix Hmm never mind, it turned out I got stuck with the old version of master. I don't know why I still had the old version that was 6 months old :( 

Closing this issue.

**Comment by haruelrovix** [comment]
@theodorusyoga 😄 

When working on forked repo, make sure to pull the `upstream` first.

```
git pull upstream master
```

An example:

```
➜  react-native-elements git:(test/increase-coverage-for-socialicon) git remote -v
origin	https://github.com/haruelrovix/react-native-elements.git (fetch)
origin	https://github.com/haruelrovix/react-native-elements.git (push)
upstream	https://github.com/react-native-elements/react-native-elements (fetch)
upstream	https://github.com/react-native-elements/react-native-elements (push)
```

If you still want to contribute to this repo, please check this issue: https://github.com/react-native-elements/react-native-elements-storybook/issues/17.

**Comment by theodorusyoga** [comment]
@haruelrovix sure 😄 realized I forgot to add upstream on my forked repo. Will look into that issue
